
ALTER TABLE users
    MODIFY COLUMN role ENUM('DM','PLAYER','USER','ADMIN') NOT NULL DEFAULT 'USER';

UPDATE users
SET role = 'USER'
WHERE role IN ('DM','PLAYER');

ALTER TABLE users
    MODIFY COLUMN role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER';
